version: '2'

services:

  base:
    build:
      context: .
    entrypoint: flask run --host=0.0.0.0
    env_file: .env
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
    working_dir: /home/geolambda
    ports:
      - "5000:5000"
    volumes:
      - '.:/home/geolambda'

  test:
    build:
      context: .
    entrypoint: bash -c 'nosetests --nologcapture -v -s -w /home/geolambda/;'
    env_file: .env
    volumes:
      - '.:/home/geolambda'

  package:
    build:
      context: .
    command:  /home/geolambda/scripts/publish.sh
    working_dir: /home/geolambda
    volumes:
      - '.:/home/geolambda'
