service: palm-risk-poc

provider:
  name: aws
  runtime: python2.7
  timeout: 120
  profile: palm
  memorySize: 3008
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/lambda_basic_execution
  deploymentBucket: palm-risk-poc
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::palm-risk-poc'

package:
  artifact: dist/raster-ops-deploy.zip

functions:
  glad-alerts:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

