service: palm-risk-poc

provider:
  name: aws
  runtime: python2.7
  timeout: 300
  profile: palm
  memorySize: 1536
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/lambda_basic_execution
  deploymentBucket: palm-risk-poc
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::palm-risk-poc'

package:
  artifact: dist/raster-ops-deploy.zip

functions:
  mill:
    handler: handler.mill

  receiver:
    handler: handler.receiver
    events:
      - http:
          path: mill
          method: get
          cors: true
