service: palm-risk-poc

provider:
  name: aws
  runtime: python2.7
  timeout: 300
  profile: palm
  memorySize: 1536
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/lambda_basic_execution
  deploymentBucket: palm-risk-poc
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::palm-risk-poc'

package:
  artifact: dist/raster-ops-deploy.zip

functions:
  umd-loss-gain:
    handler: mock_api.umd_loss_gain
    events:
        - http:
            path: umd-loss-gain
            method: post
            cors: true

  analysis:
    handler: mock_api.analysis
    events:
      - http:
          path: analysis
          method: post
          cors: true

  landcover:
    handler: mock_api.landcover
    events:
      - http:
          path: landcover
          method: post
          cors: true

  loss_by_landcover:
    handler: mock_api.loss_by_landcover
    events:
      - http:
          path: loss-by-landcover
          method: post
          cors: true
